Adding support for sonar.findbugs.onlyAnalyze
spotbugs/sonar-findbugs pull request #262
Opened 2019-04-03 05:13 UTC by akhil-developer

### Creating support for onlyAnalyze option

#### Preface
Both `spotbugs` and `findbugs` support the usage of `-onlyAnalyze` option via commandline and GUI
The purpose of this option is to restrict the analysis to only the specified class file. 
This option is of great use when running the plugins in CI / CD pipeline to support the incremental code quality checks.
However, this option is not supported in the implementation of sonar-findbug plugin and hence, it is not possible to use SonarQube in CI / CD pipeline for maintaining the incremental code quality.

#### Merits of this options.
With this option, now it is possible to restrict the SonarQube analysis to ***only given set of files/packages*** in the build pipeline, thereby considerably reducing the build time, at the same time ensuring the code quality of the change set of files.
This option can be used in the companies inbuild script to perform analysis quickly and act according to the result *ex: Failing the pre-merge only in case of fatal bugs*

#### About the new option
There are two ways to implement this in existing source.
- Create a `ClassScreener` object based on the `sonar.findbugs.onlyAnalyze`  property and set this screener in FindBug2 engine in `FindbugsExecutor#117` using `engine.setClassScreener(IClassScreener classScreener)`.
With this approach, there are un-necessary checks on other files *(which user doesnot intend)* thereby making the approach extremely in-efficient.
- ***[Implemented]*** Create a `ClassScreener` object in the configuration and include only the files which user intend to analysis. And the usual process remains the same.

#### Testing
The test cases are include to ensure that the `ClassScreener` is created and behaving correctly and as expected

2019-04-03 06:54 UTC, KengoTODA commented
Changes are LGTM.

@akhil-developer How you'll generate `sonar.findbugs.onlyAnalyze` property? I guess that you generate it in CI process? I want to grasp whole operation process of this feature.


BTW SonarQube has [the PR analysis feature](https://docs.sonarqube.org/latest/analysis/pull-request/) that may fulfill the requirement, but it is activated only in Developer Edition and above.

2019-04-09 00:13 UTC, aristotelesneto commented
I've just come across this pull request which I believe will resolve a problem I'm having.

In using SAP Hybris, they bundle an ant task that allows the code to be analysed with Sonar (ant sonarcheck), which uses sonar:sonar . This runs for each module (extension). 

The problem is that, when using Findbugs, it appears to ignore the filtered list of paths and instead is scans the module and its dependencies are scanned each and every time a new module is scanned, as opposed to only the files that have been indexes. This results in the scan taking around 10 minutes per module (as opposed to seconds).

I've tried playing around with e filter exclude file with no success on speeding up the process. I've not tested whether this particular PR would address this use case, but the onlyAnalyze option was going to be my next avenue.

What is the likelihood of this PR being merged?

2021-11-16 12:24 UTC, vincebrechbuehl commented
@KengoTODA: We have the same issue with a identical development scenario with SAP Commerce Cloud (aka Hybris) like @aristotelesneto commented on 9 Apr 2019. In a Jenkins piepline step we run a sonar check which runs 11 custom-code modules which  takes overall 65minutes to analyze. Is there planned to merge this PR into the offical version of master branch? Or we have to fork the master branch and merge it to our own fork branch to build a own plugin artefakt?

2021-11-24 07:51 UTC, gtoison commented
Hello @vincebrechbuehl , the project was dormant because the maintainer was very busy on other projects.
It was recently transferred and the first task was to make the plugin compatible with SonarQube 9.

Regarding this issue I have the feeling that there are several problems explaining the long time it takes to analyze a project. 
In particular some class folders seem to be analyzed multiple times for multi module projects (see https://github.com/spotbugs/sonar-findbugs/pull/349).
If I understand correctly SpotBugs also runs all the rules, even if they are disabled in the quality profile, so there might be potential improvements here.
I've also submitted a PR in SpotBugs itself since I've observed that one detector might have room for improvement (it is taking half of entire analysis time), see https://github.com/spotbugs/spotbugs/pull/1833

I think that the first step should be adding some integration tests (the current unit tests do not really test that SpotBugs runs), so I would be more comfortable changing things, then trying to improve performance.

2022-02-08 17:31 UTC, gtoison requested changes

2022-02-08 17:31 UTC, gtoison commented on src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
> +        .category(CoreProperties.CATEGORY_JAVA)
`Java.KEY` needs to be used instead of `CoreProperties.CATEGORY_JAVA` for compatibility with SonarQube 9

2022-03-22 08:24 UTC, gtoison commented
This can be closed now that https://github.com/spotbugs/sonar-findbugs/pull/483 has been merged in

2022-03-22 08:24 UTC, closed without merging